### ISSUE TITLE
PYPI tar file doesn't have template files

### ISSUE THREAD

**Issue by bdjohnsen** [pyecore/pyecoregen#12]
It appears that the tar file on PYPI (https://pypi.python.org/pypi/pyecoregen) doesn't have the templates included.

I tried to install it from the tar file and ran into errors that said the template files couldn't be found.

I looked through the tar file and didn't see them but when looked through the wheel file I found them.

I reinstalled using the wheel file and everything worked.

I couldn't figure out how to report the issue on PYPI so thought I would post here.

Thanks,
Ben

**Comment by aranega** [comment]
Thanks for the report! I'm the one that screwed the packaging (pretty sure), I take a look asap.

**Comment by moltob** [comment]
@aranega please create the new release if you like, I won't get to it tonight.

**Comment by aranega** [comment]
@moltob I'm on it!
