### ISSUE TITLE
Documentation generation

### ISSUE THREAD

**Issue by hsd-dev** [pyecore/pyecoregen#35]
Is it possible to generate documentation from an ecore model using this tool? If the feature is currently not available, could you give me some pointers to start?

**Comment by aranega** [comment]
Hi @ipa-hsd, 

Sorry for the late answer.

By generating documentation, do you mean generating comments/doc for each method/class/attribute in the generated code if some `EAnnotations` exist on the element, or do you refer to the generation of a kinf of textual representation of the metamodel for documentation purposes?

**Comment by hsd-dev** [comment]
I mean this
> generation of a kinf of textual representation of the metamodel for documentation purposes?

For now I converted the ecore meta-model to json schema and used https://github.com/coveooss/json-schema-for-humans for generating html and md. But would be nice to generate the documentation directly from ecore, because some information is lost in a json schema.

**Comment by aranega** [comment]
That's definitely true and a good point. The thing with `pyecoregen` is that it's tailored for Python code generation only. It doesn't mean that it's not possible to modify it to generate a documentation as you propose. 

Basically, there is three approaches that could be use:

* directly use pyecore to load the ecore metamodel and traverse it to print/generate the documentation,
* use [`pymultigen`](https://github.com/moltob/pymultigen) (on which is based pyecoregen) to rewrite the different stage of a dedicated generator, but this approach seems to me more complicated as it implies a little bit of boilerplate code to have everything running,
* use [`motra`](https://github.com/pyecore/motra), which is still a little bit experimental, but is supposed to be more or less an equivalent of QVTo and Acceleo and let you generate code for any pyecore model/metamodel using mako syntax.

**Comment by hsd-dev** [comment]
Great! That was helpful. So sounds like you would prefer option 1. I will start experimenting with it, but might need your inputs from time to time. Maybe I will create an issue to track its progress. 
Would it make sense to integrate it in `pyecoregen` as an option, something like `--gen-doc`?

**Comment by aranega** [comment]
All depends on the complexity of what you want to generate. If the final code isn't so complicated, I would use `motra` as it will really be easy to prototype something. However, if the code starts to be really complicated, I would use the first solution.

That would be definitely really cool and valuable to have the documentation generation, but I wonder if it wouldn't make sense to directly have it in pyecore as pyecoregen is really here for the python code generation. Even if you use dynamic metamodels, I guess it could make sense to want to generate the documentation and it would feel a little bit weird to have to install pyecoregen to generate it if you don't want to generate the actual python code.

**Comment by hsd-dev** [comment]
I get your point and makes sense. Thanks for the discussion! I will close the issue for now.
