### ISSUE TITLE
Import error when using freshly installed pyecoregen

### ISSUE THREAD

**Issue by ecba** [pyecore/pyecoregen#6]
After fresh installation of this library, the command line tool is throwing the following error message:

```
>pyecoregen -h
Traceback (most recent call last):
  File "C:\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Nina\ninaenv\Scripts\pyecoregen.exe\__main__.py", line 5, in <module>
  File "c:\nina\ninaenv\lib\site-packages\pyecoregen\cli.py", line 7, in <module>
    import pyecore.resources
  File "c:\nina\ninaenv\lib\site-packages\pyecore\resources\__init__.py", line 2, in <module>
    from . import xmi
  File "c:\nina\ninaenv\lib\site-packages\pyecore\resources\xmi.py", line 4, in <module>
    from lxml import etree
ImportError: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.
```

Probably some dependency (lxml) is missing.

@varanega: I am a coworker of Mike...

**Comment by moltob** [comment]
The used version of python is CPython 3.6 on Windows 7 64 Bit. lxml was installed from corresponding wheel on PyPI. .pyd extensions seem to be available... Need to look into this.

**Comment by aranega** [comment]
Perhaps I missed a thing during the `setup.py` configuration. I think I still have a windows VM, I can run som tests if it can help you?

**Comment by moltob** [comment]
Indeed it looks like something is weird with the setup of pyecore's XMI support. I will try to reproduce first and narrow it down.

**Comment by moltob** [comment]
The effect cannot be reproduced in my environment. On Windows 7 64 Bit, Python 3.6.1 64 Bit I did:

```
> py -3.6 -m venv env
> env\Scripts\activate.bat
> pip install pyecoregen
> pyecoregen -h
```

The result ts the expected behavior (help message). On the OP's machine I did the exact same thing with Python 3.6.0 64 bit and the error surfaced. I asked @ecba to rerun with a newer Python patch level and report the result here.

**Comment by ecba** [comment]
I just retried it with Python 3.6.1 and it works fine now. 
Thank you for your support!
